### ISSUE TITLE
Credential Options are stored in the Cache based on IP

### ISSUE THREAD

**Issue by danclaytondev** [m1guelpf/laravel-fastlogin#1]
During the registration process, the PublicKeyCredentialCreationOptions are created for the desired user and send to the browser to register a key. They are then stored in the cache, for validating the registration process (the server needs to keep the creation options stored).
The options are stored in the cache keyed like this:
``` 
protected function getCacheKey()
{
    return 'fastlogin-request-'.sha1(request()->getHttpHost().request()->ip());
}
```

The cache is the same across all users, and this keys on IP, so if two users were registering or logging in at the same time (within 5 minutes) in a house/office/cafe where the ip is not unique, then it is very possible that cache will return the options for the wrong user, and the registration will fail for both users.
Note, I don't think there is any security risk, as the options are never returned from the cache to the users but I do think it could fail registration for both of them. If is certainly possible that two users in an office might be logging in at the same time.

Is there any reason that we can't store the creation/login options in the session? The session is what Jetstream/Fortify uses for two factor authentication challenges.

I'm really excited to use this package, so if there is no problem with the session, I would be happy to have a go at a PR. :)

**Comment by TechTailor** [comment]
I think storing the sessions would be a good idea. A PR for that would be nice, I will have a go at that aswell.

PS> @m1guelpf Love the package, thankyou for it (was actually planning on building one myself for a project, guess don't need to now). 

-TT

**Comment by m1guelpf** [comment]
Hey @danclaytondev @TechTailor!

I was originaly storing those in the session, but there were some issues in Laravel Vapor that regenerated the CSRF token, making the second AJAX request fail. I think we need to use the cache to be safe here, although I'd welcome a PR that adds more differentiation to the cache key.
