### ISSUE TITLE
Issue with migration

### ISSUE THREAD

**Issue by temokasab** [m1guelpf/laravel-fastlogin#12]
I could not migrate without renaming migration class to "CreateCredentialsTable". Don't know if this bug is just for me or for everyone. I have Laravel v8. Please check it out. I think it is because migration name, and class differance. 
BTW Great Package. Thank you. 
![Capture](https://user-images.githubusercontent.com/65551299/124195002-999f1f00-dada-11eb-9fdc-2de0b8cb13d8.PNG)

**Comment by romanmartushev** [comment]
#11 fixes this.
