### ISSUE TITLE
Cookie not available in JS or Laravel

### ISSUE THREAD

**Issue by captenmasin** [m1guelpf/laravel-fastlogin#13]
I've just installed the package on a fairly simple Laravel app however after setting up and enabling fastlogin, when I try to login it can't seem to access the "X-FastLogin" cookie, either in the actual JS or when dd-ing $request

<img width="445" alt="Screenshot 2021-07-02 at 9 39 09 pm" src="https://user-images.githubusercontent.com/25454872/124326428-4383b780-db7e-11eb-9260-462bc55c371d.png">

I can see that it's there in the cookies section of inspect element but if I run `alert(Cookies.get('X-FastLogin'))` on click, it returns undefined

<img width="1530" alt="Screenshot 2021-07-02 at 9 41 00 pm" src="https://user-images.githubusercontent.com/25454872/124326460-53030080-db7e-11eb-9d6f-47f3a6d37468.png">
<img width="494" alt="Screenshot 2021-07-02 at 9 41 07 pm" src="https://user-images.githubusercontent.com/25454872/124326464-54342d80-db7e-11eb-9ca8-baec63e5d535.png">

**Comment by captenmasin** [comment]
Looking into it a bit more it seems it's because the cookie is set as "HttpOnly"
I'm not sure if this is an issue with the package or my app setup though

**Comment by captenmasin** [comment]
I've also just noticed I'm supposed to be getting the XSRF-TOKEN... It's been a long day

**Comment by captenmasin** [comment]
Okay SO
Apologies for this thread it's a mess but this is the full error I'm getting when posting to `/fastlogin/login/details`

```php
exception: "TypeError"
file: "/home/ploi/dev.myboard.co-deploy/dev.myboard.co/01072021_203247/vendor/web-auth/webauthn-lib/src/PublicKeyCredentialDescriptor.php"
line: 49
message: "Webauthn\\PublicKeyCredentialDescriptor::__construct(): Argument #2 ($id) must be of type string, null given, called in /home/ploi/dev.myboard.co-deploy/dev.myboard.co/01072021_203247/vendor/m1guelpf/laravel-fastlogin/src/Http/Controllers/FastLoginController.php on line 78
```

**Comment by m1guelpf** [comment]
Closing in favour of #14
