### ISSUE TITLE
If your application does not globally disable Model Guarding, It doesn't work

### ISSUE THREAD

**Issue by JapSeyz** [m1guelpf/laravel-fastlogin#2]
[This line](https://github.com/m1guelpf/laravel-fastlogin/blob/main/src/Http/Controllers/FastLoginController.php#L63) fails if the Default Laravel setup is used w/ model guarding.

I'd be happy to either PR an addition to the docs to mention this, or make the changes to the credentials model to add a $fillable array, depending on your preference

**Comment by jouniikaheimo** [comment]
i not sure is same issue but i got error:
    "message": "Call to a member function map() on null",
    "exception": "Error",
    "file": "***/vendor/m1guelpf/laravel-fastlogin/src/Http/Controllers/FastLoginController.php",
    "line": 43,

**Comment by JapSeyz** [comment]
That's because you need to add this [trait ](https://github.com/m1guelpf/laravel-fastlogin/blob/main/src/Models/Concerns/CanFastLogin.php) to your user model

**Comment by jouniikaheimo** [comment]
Yeah this help that.. but no browser want select authentication method but if i try use fingerprint censor or youbikey nothing happened...

**Comment by JapSeyz** [comment]
What does your console say? Most likely you'll find either a JS or a Laravel exception

**Comment by jouniikaheimo** [comment]
<img width="380" alt="kuva" src="https://user-images.githubusercontent.com/32259223/105839122-ae323500-5fd9-11eb-8c7f-bdd2f0f062da.png">

i got this ... no error in console and no post request... 

i convert that javascript jquery request possible issue is this.. if you are example code register / login javascripts i can test

**Comment by jouniikaheimo** [comment]
now i got error message in js 

DOMException: The request is not allowed by the user agent or the platform in the current context, possibly because the user denied permission.

**Comment by JapSeyz** [comment]
> now i got error message in js
> 
> DOMException: The request is not allowed by the user agent or the platform in the current context, possibly because the user denied permission.

Are you running it on an HTTPS page? The credentials manager is only available on HTTPS pages, not HTTP

**Comment by jouniikaheimo** [comment]
Yes https

**Comment by iMusicJJ** [comment]
> Yes https 

Please create a reproducible codesandbox or the likes where I can see the code.

**Comment by JapSeyz** [comment]
Please create a reproducible codesandbox where I can see the code.

**Comment by jouniikaheimo** [comment]
```

            const register = () => {
                const token = Cookies.get('XSRF-TOKEN')

                useRegistration({
                    actionUrl: '{{ route('fastlogin.create')  }}',
                    optionsUrl: '{{ route('fastlogin.create.details')  }}',
                    actionHeader: {
                        'x-xsrf-token': token
                    },
                }, {
                    'x-xsrf-token': token
                })().then(() => {
                    // credential has been added
                })
            }

             document.getElementById('register12').addEventListener('click', register)
```

i changed javascripts this and register12 is new button jetstream profile view...

**Comment by JapSeyz** [comment]
Codesandbox please, so we can see the entire code.

It could easily be how the `Cookies` is imported or the `useRegistration` since that is not part of the pasted code.

**Comment by jouniikaheimo** [comment]
ah issue solved :) fastlogin need "nyholm/psr7" and symfony/psr-http-message-bridge and this is not requirements in composer.json

**Comment by jouniikaheimo** [comment]
@JapSeyz yeah only issue is this two package missing.. but now i'm not know how i can choise different method... fingerprint or usb key... browsers not allow select method

**Comment by m1guelpf** [comment]
Will work on fixing all of this, thanks for looking into it!
