### ISSUE TITLE
Getting CSRF token mismatch error

### ISSUE THREAD

**Issue by kabircse** [m1guelpf/laravel-fastlogin#31]
Normal ajax call working fine on that page but useLogin giving csrf error.

my code as:

            //const token = $('meta[name="csrf-token"]').attr('content');
            const token = Cookies.get('XSRF-TOKEN');
            
            useLogin({
                    actionUrl: 'http://localhost:8000/fastlogin/login',
                    optionsUrl: 'http://localhost:8000/fastlogin/login/details',
                    actionHeader: {
                        'x-xsrf-token': token
                    },
                }, {
                    'x-xsrf-token': token
                })().then(() => {
                    // credential has been added
                    console.log('credential has been added.');
                })
                
                
Is there anything wrong ?

**Comment by patrocle** [comment]
Hello,
I had the same issue ;-)

```
const token =  document.querySelector('meta[name="csrf-token"]').getAttribute('content');
useLogin({
    actionUrl: route('fastlogin.login'),
    optionsUrl: route('fastlogin.login.details'),
    actionHeader: {
        'X-CSRF-TOKEN': token
    },
    optionsHeader: {
        'X-CSRF-TOKEN': token
    }
}, {
    'X-CSRF-TOKEN': token
})().then(() => {
    window.location.reload()
})
```

**Comment by kabircse** [comment]
> Hello, I had the same issue ;-)
> 
> ```
> const token =  document.querySelector('meta[name="csrf-token"]').getAttribute('content');
> useLogin({
>     actionUrl: route('fastlogin.login'),
>     optionsUrl: route('fastlogin.login.details'),
>     actionHeader: {
>         'X-CSRF-TOKEN': token
>     },
>     optionsHeader: {
>         'X-CSRF-TOKEN': token
>     }
> }, {
>     'X-CSRF-TOKEN': token
> })().then(() => {
>     window.location.reload()
> })
> ```

Thanks for your reply. Now it's working but getting another error.

           "message": "Argument 2 passed to Webauthn\\PublicKeyCredentialDescriptor::__construct() must be of the type string, null given, called in FastLoginController.php on line 108".
           
           
           Have you any idea ? Thanks in advance.

**Comment by patrocle** [comment]
It may be linked to the PR I just made #32
