### ISSUE TITLE
PHP 7 Support

### ISSUE THREAD

**Issue by erfanhemmati** [m1guelpf/laravel-fastlogin#7]
i have some errors.
(Package m1guelpf/laravel-fastlogin at version  has a PHP requirement incompatible with your PHP version, PHP extensions and Composer version)

my php version: 7.4.9
my composer version: 2.0.0-RC1
my laravel application version: 7.30.1

**Comment by niladam** [comment]
@erfanhemmati apparently, the packages' composer.json requires PHP 8.0.

@m1guelpf Are there any reasons to this high PHP requirement ? Do you need help testing it in lower versions ?

**Comment by m1guelpf** [comment]
@niladam I used named arguments to clean up the code, so it could potentially support older versions, but at the expense of code clarity.

**Comment by niladam** [comment]
@m1guelpf while i know that there are great number of advantages in PHP 8.0, i think sticking to illuminate's current support (which is currently **^7.4|^8.0**) will actually improve this package's adoption rates.

Personally, i think it would be better in the long run.

Yes, PHP 8.0 is fancy and yes it does clean up alot of code (yay property promotion!) but i second the requirement for maybe 7.4 and upwards.

If you need help with anything do let me know and i'll do my best!

**Comment by niladam** [comment]
@erfanhemmati i also suggest you change the title of this issue to maybe something like: 'Minimum PHP requirements error' ?

**Comment by erfanhemmati** [comment]
@niladam thanks

**Comment by m1guelpf** [comment]
This has been added on the new release!
